import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useState } from "react";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

interface Dialogue {
  id: number;
  text: string;
  character: string;
  series: string;
}

interface HomeProps {
  dialogues: Dialogue[];
}

export default function Home(props: HomeProps): JSX.Element {
  console.log(props);
  const [dialogueId, setDialogueId] = useState<number | undefined>();

  return (
    <>
      <Head>
        <title>Dialogues</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header />
        <div className={styles.center}>
          <h1>Dialogues</h1>
        </div>
        <div className={styles.grid}>
          {props.dialogues.map((item, index) => {
            return (
              <div className={styles.card} key={index}>
                {item.text.length <= 45 ? (
                  <h2>{item.text}</h2>
                ) : dialogueId !== item.id ? (
                  <h2>
                    {`${item.text.slice(0, 45)}...`}
                    <p
                      style={{ cursor: "pointer", textDecoration: "underline" }}
                      onClick={() => setDialogueId(item.id)}
                    >
                      show more
                    </p>
                  </h2>
                ) : (
                  <h2>
                    {item.text}
                    <p
                      style={{ cursor: "pointer", textDecoration: "underline" }}
                      onClick={() => setDialogueId(undefined)}
                    >
                      show less
                    </p>
                  </h2>
                )}
                <p>By: {item.character}</p>
                <p>From: {item.series}</p>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}

// ssr
export async function getServerSideProps() {
  // Fetch data from external API
  const getDialogues = async () => {
    try {
      const response = await axios.get<Dialogue[]>(
        "https://wordsapi-nkj3.onrender.com/dialogues"
      );
      return response.data;
    } catch (error) {
      console.error(error);
      return [];
    }
  }

  const dialogues = await getDialogues();

  // Pass data to the page via props
  return { props: { dialogues } };
}

